lib/engine/config/routes.rb
Engine::Application.routes.draw do
  root 'info#index'

  resources :info
  resources :content do
    collection do
      get :search
      post :delete
      post :change_database
    end
  end

  resources :performance do
    collection do
      get :check
    end
  end

  resources :tasks
  resources :notifications

end

lib/engine/app/models/notification.rb
class Notification < ActiveRecord::Base
  default_scope ->{order('created_at DESC')}

  def when
    created_at.localtime.strftime('%Y/%m/%d %H:%M')
  end
end

lib/engine/app/models/task.rb
class Task < ActiveRecord::Base
  ACTIVE = 'active'.freeze
  INACTIVE = 'inactive'.freeze
  DEFAULT_INTERVAL = 60
  DEFAULT_DATABASE = 0

  store :data
  after_initialize :init

  def init
    self.every ||= DEFAULT_INTERVAL
    self.database ||= DEFAULT_DATABASE
  end

  def self.selectable_actions
    [['Watch key', WatchKeyTask], ['Watch query', WatchQueryTask]]
  end

  def active?
    status == ACTIVE
  end

  def to_partial_path
    'tasks/task'
  end

  def reset_queue
    BackgroundTaskJob.new(self).reset_queue
  end

  def backend
    BackendConnection.build(current_database: self.database)
  end
end

lib/engine/app/models/watch_key_task.rb
class WatchKeyTask < Task
  def type_name
    'Watch key'
  end

  def perform
    result = RetrieveKey.new(backend, trigger).result
    if data[:initialized]
      notify(data[:old_value], result) if data[:old_value] != result
    else
      data[:initialized] = true
    end

    data[:old_value] = result
    save
  end

  def notify(old_value, new_value)
    msg = "Value of key '#{trigger}' has changed from #{old_value.inspect} to #{new_value.inspect}"
    Notification.create(reporter: name, message: msg)
  end
end

lib/engine/app/models/watch_query_task.rb
require 'active_support/core_ext/hash/indifferent_access'

class WatchQueryTask < Task
  def type_name
    'Watch query'
  end

  def perform
    result = SearchKeys.new(backend, trigger).result.map(&:with_indifferent_access)
    if data[:initialized]
      notify(data[:old_value], result) if data[:old_value] != result
    else
      data[:initialized] = true
    end

    data[:old_value] = result
    save
  end

  def notify(old_value, new_value)
    msg = "Value of key '#{trigger}' has changed from #{old_value.inspect} to #{new_value.inspect}"
    Notification.create!(reporter: name, message: msg)
  end
end

lib/engine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from Redis::CannotConnectError, :with => :redis_not_available

  helper_method :backend

  if Authentication.authentication_required?
    http_basic_authenticate_with name: Authentication.credentials[:user], password: Authentication.credentials[:password]
  end

  def backend
    @backend ||= BackendConnection.build(current_database: session[:database])
  end

  def redis_not_available
    render 'layouts/redis_not_available'
  end
end

lib/engine/app/controllers/content_controller.rb
class ContentController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_section
  before_action :load_database_list, only: [:index, :search]
  before_action :load_current_database, only: [:index, :search]

  def index
  end

  def search
    results = SearchKeys.new(backend, params[:key]).result
    @results = results.paginate(:page => params[:page], :per_page => 20)
  end

  def delete
    RemoveKey.new(backend, params[:key]).execute
    redirect_to :back
  end

  def change_database
    ChangeDatabase.new(backend, session, params[:database]).execute
    redirect_to :back
  end

  private
  def load_section
    @section = 'content'
  end

  def load_database_list
    @databases = DatabaseList.new(backend).result
  end

  def load_current_database
    @current_database = backend.current_database
  end
end

lib/engine/app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
    @section = 'info'
    @info = backend.info
  end
end

lib/engine/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_section

  def index
    @notifications = Notification.paginate(:page => params[:page], :per_page => 20)
  end

  def destroy
    notification = Notification.find(params[:id])
    notification.destroy
    redirect_to action: :index
  end

  private
  def load_section
    @section = 'notifications'
  end
end

lib/engine/app/controllers/performance_controller.rb
class PerformanceController < ApplicationController
  before_action :load_section

  def index
  end

  def check
    @stats = PerformanceStats.new(backend).result
  end

  private
  def load_section
    @section = 'performance'
  end
end

lib/engine/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_section
  after_action :reset_queue, only: [:create, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.create(task_params)
    redirect_to action: :index
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    redirect_to action: :index
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to action: :index
  end

  private
  def load_section
    @section = 'tasks'
  end

  def task_params
    params.require(:task).permit(:name, :type, :trigger, :database, :every, :status)
  end

  def reset_queue
    @task.reset_queue
  end
end

lib/engine/app/helpers/application_helper.rb
module ApplicationHelper
  def selected_is_selected(section, selected)
    'active' if section == selected
  end

  def section(opts = {})
    haml_tag :li, class: selected_is_selected(opts[:name], opts[:selected_section]) do
      haml_tag :a, opts[:title], href: opts[:url]
    end
  end

  def content_menu(selected_section)
    capture_haml do
      haml_tag :ul, class: 'nav navbar-nav' do
        section(name: 'info', title: 'Info', url: info_index_path, selected_section: selected_section)
        section(name: 'content', title: 'Content', url: content_index_path, selected_section: selected_section)
        section(name: 'tasks', title: 'Tasks', url: tasks_path, selected_section: selected_section)
        section(name: 'notifications', title: 'Notifications', url: notifications_path, selected_section: selected_section)
        section(name: 'performance', title: 'Performance', url: performance_index_path, selected_section: selected_section)
      end
    end
  end

  def remove_class
    'btn btn-danger'
  end

  def edit_class
    'btn btn-primary'
  end

  def redis_configuration_string
    "#{backend.host}:#{backend.port}"
  end
end

lib/engine/app/helpers/database_helper.rb
module DatabaseHelper
  def databases(dbs)
    dbs.each do |database|
      database_option(database)
    end
  end

  def database_option(database)
    haml_tag :option, {selected: (database.to_i == @current_database.to_i)} do
      haml_concat database
    end
  end

  def choose_database_select(dbs)
    capture_haml do
      haml_tag :form, action: '/content/change_database', method: 'post' do
        haml_tag :div, class: 'form-group' do
          haml_tag :label, for: 'database_select' do
            haml_concat 'Select database'
          end

          haml_tag :select, id: 'database_select', name: 'database', class: 'selectpicker form-control', data: {style: 'btn-info'} do
            databases(dbs)
          end
        end
      end

    end
  end

end

lib/engine/app/helpers/pagination_helper.rb
require 'will_paginate-bootstrap'

module PaginationHelper
  def bootstrap_paginate(results)
    will_paginate results, renderer: BootstrapPagination::Rails, previous_label: '<<', next_label: '>>'
  end
end

lib/engine/app/views/content/_search_form.haml
- search_term ||= nil

= choose_database_select(@databases)
%hr

%form{action: search_content_index_path, method: 'get', style: 'margin-top: 5px'}
  .form-group
    %label{for: 'input_key'}
      Introduce search terms (wildcards allowed)
    %input.form-control{type: 'text', id: 'input_key', name: 'key', placeholder: 'Search terms', value: search_term}
  .form-group
    %button{type: 'submit', class: remove_class}
      Search

lib/engine/app/views/content/index.haml
= render 'search_form'

lib/engine/app/views/content/search.haml
= render 'search_form', search_term: params[:key]

%table.table.table-striped
  %thead
    %tr
      %th
        Key
      %th
        Value
      - if Authorization.authorized_for?(:remove_content)
        %th
          Actions

  %tbody
    - @results.each do |result|
      %tr
        %td
          = result[:key]
        %td
          = result[:value]
        - if Authorization.authorized_for?(:remove_content)
          %td
            %form{action: '/content/delete', method: 'post'}
              %input{type: 'hidden', name: 'key', value: result[:key]}
              %button.btn.btn-danger
                Delete

= bootstrap_paginate @results

lib/engine/app/views/info/index.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Parameter
      %th
        Value

  %tbody
    - @info.each do |parameter, value|
      %tr
        %td
          = parameter
        %td
          = value

lib/engine/app/views/layouts/application.haml
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    = stylesheet_link_tag 'bootstrap.min', media: 'all'
    = stylesheet_link_tag 'bootstrap-select.min', media: 'all'
    = stylesheet_link_tag 'custom', media: 'all'

    = javascript_include_tag 'jquery-2.0.3.min'
    = javascript_include_tag 'jquery_ujs'
    = javascript_include_tag 'bootstrap.min'
    = javascript_include_tag 'bootstrap-select.min'
    = javascript_include_tag 'app'

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: '/'}
            Redis Monitor
        .collapse.navbar-collapse
          = content_menu(@section)

    .container
      = yield

lib/engine/app/views/layouts/redis_not_available.haml
.message_centered
  = "Can not connect to redis instance #{redis_configuration_string}"

lib/engine/app/views/notifications/_notification.haml
%tr
  %td
    = notification.reporter
  %td
    = notification.message
  %td
    = notification.when
  %td
    = link_to 'Delete', notification_path(notification), class: remove_class, :confirm => 'Are you sure?', :method => :delete

lib/engine/app/views/notifications/index.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Reporter
      %th
        Message
      %th
        When
      %th
        Actions

  %tbody
    = render @notifications

= bootstrap_paginate @notifications

lib/engine/app/views/performance/check.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Parameter
      %th
        Value

  %tbody
    - @stats.each do |parameter, value|
      %tr
        %td
          = parameter
        %td
          = value

lib/engine/app/views/performance/index.haml
.message_centered
  This action could take a while.
  %a{href: '/performance/check'}
    Proceed

lib/engine/app/views/tasks/_form.haml
= form_for @task.becomes(Task) do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :type, 'Action'
    = f.select(:type, options_for_select(Task.selectable_actions, @task.type), {}, {class: 'form-control'})

  .form-group
    = f.label :trigger
    = f.text_field :trigger, class: 'form-control'

  .form-group
    = f.label :database, 'Database'
    = f.number_field :database, class: 'form-control'

  .form-group
    = f.label :every, 'Every (seconds)'
    = f.number_field :every, class: 'form-control'

  .form_group
    .checkbox
      = f.label :status, {style: 'font-weight:bold'} do
        = f.check_box :status, {}, Task::ACTIVE, Task::INACTIVE
        = 'Active'

  .form-group
    %button.btn.btn-default{type: 'submit', style: 'margin-right: 10px'}
      Save
    %a{href: tasks_path}
      Cancel

lib/engine/app/views/tasks/_task.haml
%tr
  %td
    = task.name
  %td
    = task.type_name
  %td
    = task.trigger
  %td
    = task.every
  %td
    = task.active? ? 'Yes' : 'No'
  %td
    = link_to 'Edit', edit_task_path(task), class: edit_class
    = link_to 'Delete', task_path(task), class: remove_class, :confirm => 'Are you sure?', :method => :delete

lib/engine/app/views/tasks/edit.haml
%h2
  Edit task
= render 'form'

lib/engine/app/views/tasks/index.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Name
      %th
        Action
      %th
        Trigger
      %th
        Every (seconds)
      %th
        Active
      %th
        Actions

  %tbody
    = render @tasks

%a.btn.btn-default{href: new_task_path}
  New task

lib/engine/app/views/tasks/new.haml
%h2
  New task
= render 'form'